### ISSUE TITLE
Doesn't seem to be working for me. Cannot read property 'click' of undefined

### ISSUE THREAD

**Issue by xcloudx01** [ian-campbell/Erasure#3]
VM388:8 Uncaught TypeError: Cannot read property 'click' of undefined
    at itemClick (<anonymous>:8:107)

**Comment by ian-campbell** [comment]
Will check into it, thank you. This has been a recurring problem. I am traveling in a country with unreliable internet to say the least so give me a few days and we’ll get it working.

**Comment by indig0F10w** [comment]
It works when YouTube is set to new design, if you changed the cookie value so it displays old design it will not do anything.

The script cannot delete comments from deleted or private videos, you need to do that manually. I used Chrome extension.

P.S. This is the greatest script ever written, thank you!

**Comment by ian-campbell** [comment]
> The script cannot delete comments from deleted or private videos, you need to do that manually. I used Chrome extension.

@indig0F10w I added a quick & dirty button to delete comments on private and deleted videos. Test it out for me if you get a chance. It worked on my machine, but you know how it goes. I'll combine them into a single button and fix some other issues this week.

**Comment by ian-campbell** [comment]
I added new functionality to delete comments on private videos.
