### ISSUE TITLE
Refresh required for 'delete' function to work.

### ISSUE THREAD

**Issue by OnTheGrind** [ian-campbell/Erasure#9]
The extension offers a button that will navigate to the correct corresponding page where your comments are located to be deleted. A second button is offered to delete the comments on that page.

When I click on the "click to navigate to your comment history" button, it will navigate to that page by loading in the active tab (it should open a new one, but not the complaint right now). When I click the "click to delete all comments" button, nothing happens.

Instead, I have to refresh the tab. Once that is done, it appears to work fine and starts deleting comments as expected.

I have other intermittent issues as well.

A quick fix (temporary) might be to add a page refresh into the script after the page opens, or perhaps have it open a new tab.

Video of issue attached.

![Sssssssssscreenshot from 2021-04-23 11-22-57](https://user-images.githubusercontent.com/18671146/115894178-f7eaba00-a426-11eb-9a62-66d2b3e82a97.png)

https://user-images.githubusercontent.com/18671146/115891307-f10e7800-a423-11eb-97f5-63eebeefd32a.mp4

**Comment by ian-campbell** [comment]
Script updated to open a new tab on navigation. If you could open issues for the intermittent issues you're having it would be much appreciated.
